In [35]:
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import pandas as pd

In [36]:
data = pd.read_csv("IUH - sample_01.csv")

In [37]:
data = data.head(31)
data

datetime  sales_mobile  sales_fashion  sales_groceries  Unnamed: 4
0    5/1/20          31.0           18.0             13.0         NaN
1    5/2/20          65.0           42.0              9.0         NaN
2    5/3/20          90.0           29.0             19.0         NaN
3    5/4/20          31.0           48.0             18.0         NaN
4    5/5/20          72.0           22.0             19.0         NaN
5    5/6/20          37.0           43.0             16.0         NaN
6    5/7/20          37.0           31.0             16.0         NaN
7    5/8/20          29.0           45.0              7.0         NaN
8    5/9/20          77.0           47.0              6.0         NaN
9   5/10/20          84.0           39.0              7.0         NaN
10  5/11/20          55.0           49.0              8.0         NaN
11  5/12/20          55.0           13.0              8.0         NaN
12  5/13/20          74.0           33.0             12.0         NaN
13  5/14/20          26.0           53.0              6.0         NaN
14  5/15/20          38.0           48.0             11.0         NaN
15  5/16/20          38.0           31.0             18.0         NaN
16  5/17/20          44.0           20.0              7.0         NaN
17  5/18/20          71.0           23.0             19.0         NaN
18  5/19/20          59.0           59.0             19.0         NaN
19  5/20/20          35.0           19.0             17.0         NaN
20  5/21/20          47.0           37.0             17.0         NaN
21  5/22/20          29.0           46.0              6.0         NaN
22  5/23/20          53.0           28.0             19.0         NaN
23  5/24/20          57.0           43.0             12.0         NaN
24  5/25/20          37.0           30.0              5.0         NaN
25  5/26/20          32.0           51.0             12.0         NaN
26  5/27/20          63.0           49.0             15.0         NaN
27  5/28/20          41.0           20.0              5.0         NaN
28  5/29/20          25.0           50.0             14.0         NaN
29  5/30/20          61.0           16.0             15.0         NaN
30  5/31/20          28.0           46.0             19.0         NaN

In [38]:
df = pd.read_csv("data_iuh.csv")

In [39]:
df

datetime  mobile
0          1      31
1          2      65
2          3       9
3          4      31
4          5      72
5          6      37
6          7      37
7          8      29
8          9      77
9         10      84
10        11      55
11        12      55
12        13      74
13        14      26
14        15      38
15        16      38
16        17      44
17        18      71
18        19      59
19        20      35
20        21      47
21        22      29
22        23      53
23        24      57
24        25      37
25        26      32
26        27      63
27        28      41
28        29      25
29        30      61
30        31      28

Gán cho X là mảng đơn vị ngày

In [40]:
X = df.values[:, 0].reshape(-1,1)
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31]], dtype=int64)

Gán cho y là giá trị sản phẩm mobile qua các ngày

In [41]:
y = data.values[:, 1].reshape(-1,1)
y

array([[31.0],
       [65.0],
       [90.0],
       [31.0],
       [72.0],
       [37.0],
       [37.0],
       [29.0],
       [77.0],
       [84.0],
       [55.0],
       [55.0],
       [74.0],
       [26.0],
       [38.0],
       [38.0],
       [44.0],
       [71.0],
       [59.0],
       [35.0],
       [47.0],
       [29.0],
       [53.0],
       [57.0],
       [37.0],
       [32.0],
       [63.0],
       [41.0],
       [25.0],
       [61.0],
       [28.0]], dtype=object)

In [42]:
model = LinearRegression()

tiến hành train/fit model

In [43]:
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Dự đoán cho ngày thứ 32 tương ứng là ngày 1/6/2020

In [44]:
z = np.array([32]).reshape(-1,1)
z

array([[32]])

Dự đoán cho sản phẩm mobile

In [45]:
model.predict(z)

array([[40.56129032]])

gán biến a cho giá trị của mặt hàng fashion

In [46]:
a = data.values[:, 2].reshape(-1,1)
a

array([[18.0],
       [42.0],
       [29.0],
       [48.0],
       [22.0],
       [43.0],
       [31.0],
       [45.0],
       [47.0],
       [39.0],
       [49.0],
       [13.0],
       [33.0],
       [53.0],
       [48.0],
       [31.0],
       [20.0],
       [23.0],
       [59.0],
       [19.0],
       [37.0],
       [46.0],
       [28.0],
       [43.0],
       [30.0],
       [51.0],
       [49.0],
       [20.0],
       [50.0],
       [16.0],
       [46.0]], dtype=object)

tiến hành train/fit model

In [47]:
model.fit(X, a)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Dự đoán ngày thứ 32 tương ứng là ngày 1/6 cho mặt hàng Fashion

In [48]:
model.predict(z)

array([[37.72903226]])

gán b cho giá trị của groceries

In [49]:
b = data.values[:, 3].reshape(-1,1)
b

array([[13.0],
       [9.0],
       [19.0],
       [18.0],
       [19.0],
       [16.0],
       [16.0],
       [7.0],
       [6.0],
       [7.0],
       [8.0],
       [8.0],
       [12.0],
       [6.0],
       [11.0],
       [18.0],
       [7.0],
       [19.0],
       [19.0],
       [17.0],
       [17.0],
       [6.0],
       [19.0],
       [12.0],
       [5.0],
       [12.0],
       [15.0],
       [5.0],
       [14.0],
       [15.0],
       [19.0]], dtype=object)

In [50]:
model.fit(X, b)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Cuối cùng là dự đoán cho mặt hàng groceries

In [51]:
model.predict(z)

array([[12.83225806]])